### ISSUE TITLE
Issue: Invalid Parameters

### ISSUE THREAD

**Issue by mattdbr** [dkl3/py-issuu-scrape#2]
Hi, stumbled upon your script when I was about to try my own - getting this issue (or should I say issuu) when running the script on: https://issuu.com/raywhiteofficeupdate/docs/june_2018_sydney_office_listings?e=32688446/61816242

```
Invalid Parameter - "June
Traceback (most recent call last):
  File ".\issuu.py", line 28, in <module>
    subprocess.check_call(params)
  File "C:\Users\akkat\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['convert', 'page_*', 'June 2018 sydney office listings.pdf']' returned non-zero exit status 4.
```

**Comment by jpeacock29** [comment]
You will need to [install](https://www.imagemagick.org/script/download.php) ImageMagick for its command line tool called `converter`. On OSX, you can also install this by running

    brew install converter

**Comment by jpeacock29** [comment]
This script requires the `convert` command from [ImageMagick](https://www.imagemagick.org/script/download.php) to stitch the downloaded pictures together into a pdf. Install `convert` to fix this.

**Comment by dkl3** [comment]
sorry for massive delays at responding -- i'm working into fixing this script right now. Thank you jpeacock29 for the commit

**Comment by jpeacock29** [comment]
You're welcome, @dkl3; thank you for merging!
